name: iOS Development build

on:
  workflow_dispatch:

jobs:
  build:
    name: Development build (iOS only)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get JRE8
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: depends
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-ios-aarch64

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: depends
          workflow_conclusion: completed
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre17-ios-aarch64

      - name: Get JRE21
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: depends
          workflow_conclusion: completed
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre21-ios-aarch64

      - name: Build ipa/tipa
        run: |
          export PATH=/opt/procursus/bin:/opt/homebrew/bin:$PATH
          export RUNNER=1 SLIMMED=1
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=2
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=2 TROLLSTORE_JIT_ENT=1

      - name: Upload regular ipa
        uses: actions/upload-artifact@v4
        with:
          name: pojavlauncher-ios.ipa
          path: artifacts/net.kdt.pojavlauncher-*-ios.ipa

      - name: Upload TrollStore tipa
        uses: actions/upload-artifact@v4
        with:
          name: pojavlauncher-ios.tipa
          path: artifacts/net.kdt.pojavlauncher-*-ios-trollstore.tipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@v4
        with:
          name: pojavlauncher-ios.slimmed.ipa
          path: artifacts/net.kdt.pojavlauncher.slimmed-*-ios.ipa

      - name: Upload slimmed tipa
        uses: actions/upload-artifact@v4
        with:
          name: pojavlauncher-ios.slimmed.tipa
          path: artifacts/net.kdt.pojavlauncher.slimmed-*-ios-trollstore.tipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v4
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
